# Generated by Django 3.2.16 on 2022-11-02 12:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221027_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recepie_image_file_path),
        ),
    ]
